Equivocators composition
runtimeverification/casper-cbc-proofs pull request #142
Opened 2020-11-18 07:43 UTC by traiansf

Basic composition of equivocators (where equivocating and non-equivocating machines are partitioned from the beginning).

2020-11-20 21:38 UTC, bmmoore requested changes
Looks pretty good. It's only the few explicit requests that I'd definitely like to see included in this PR, all small and local changes.

2020-11-20 21:38 UTC, bmmoore commented on VLSM/Equivocators/Projections.v
> +    match (snd l) with
I'm not specifically recommending the change, but you could consider pulling the equality outside the match by changing the conclusion to something like
```exists (oitemx: option vtransition_item X), equivocator_vlsm_transition_item_project item (Existing _ i fi) = Some (oitemx, snd l) /\ (match (snd l) with NewMatchine _ _ => oitemx = None | _ => match oitemx with Some _ => True | None => False end end)```
Of course, if you usually need to end up destructing `snd l` anyway that's only making things more awkward by sticking the `exists` where it will show up in both cases; that doesn't move the equality high enough to actually `rewrite` by the lemma.

2020-11-23 14:50 UTC, traiansf commented on VLSM/Equivocators/Common.v
> +  : projT2 (equivocator_state_extend bs s) F1 = projT2 bs F1.
I think it was useful at some point, when I was considering always projecting on the `F1` but not anymore. Seeing that it's not used anywhere, I decided to remove it.  Nevertheless, I think we could consider using a lemma like the one you proposed to shorten some of the proofs where the proof is is done explicitly within.

2020-11-23 14:57 UTC, traiansf commented on VLSM/Equivocators/Common.v
> +  induction Hbs; simplify_dep_elim; split.
you're right, they seem to be synonyms; replacing them with dependent induction worked like a charm.

2020-11-23 16:05 UTC, traiansf commented on VLSM/Equivocators/Composition/Common.v
> +Lemma equivocators_protocol_state_project
I don't have an immediate idea. I'll add an issue about it.

2020-11-24 13:26 UTC, traiansf commented on VLSM/Equivocators/MessageProperties.v
> +  : match snd (l bitem) with
i've split this one into two lemmas

2020-11-24 13:26 UTC, traiansf commented on VLSM/Equivocators/Projections.v
> +    match (snd l) with
I've split this one intro two lemmas.

2020-11-24 13:28 UTC, traiansf commented
@bmmoore I've addressed all your comments. Please take another look. In the meanwhile, I'll try to think of ways to break that huge proof.

2020-11-24 21:59 UTC, bmmoore requested changes
If you have places in mind where the generalized equivocator_state_extend_original_state could be used, please let me know.

The code changes I asked for are all good.

But I noticed two things I missed in the first review, and one change to make with tactic use in new proofs. (`change` instead of `replace ... by reflexivity`).

2020-11-24 21:59 UTC, bmmoore commented on VLSM/Equivocators/Common.v
> +      end.
If the terms are convertible you can use `change` instead of `replace ... by reflexivity`.

Writing it this way makes me wonder if there is funny setoid stuff going on. (I'm pretty that `reflexivity` cannot succeed with non-convertible terms even if you are trying to prove a setoid goal).

2020-11-24 21:59 UTC, bmmoore commented on VLSM/Equivocators/MessageProperties.v
> +      (Hitem : equivocator_vlsm_transition_item_project _ bitem d = Some (None, snd (l bitem))),
I missed this in the first review.
Unless I'm missing some implicit mentions of the existentially quantified variables, the conjuncts `input bitem = None /\ output bitem = None` should be outside the existential, and `Hitem` doesn't need to be a named parameter.
How about some permutation of
`: input bitem = None /\ output bitem = None  /\ exists (d:MachineDescriptor), equivocator_vlsm_transition_item_project _ bitem d = Some (None, snd (l bitem)).`

2020-11-24 21:59 UTC, bmmoore commented on VLSM/Equivocators/MessageProperties.v
> +      In item tr.
This conclusion also has `Hitem` and `Htr` being unnecessarily bound as quantified parameters, but both mentioning `item` makes it less obvious how to untangle dependencies. Maybe
```
exists (item: vtransition_item X),
(exists (d: MachineDescriptor),
    equivocator_vlsm_transition_item_project _ bitem d = Some (Some item, snd (l bitem)))
/\ exists (tr : list (vtransition_item X)),
In item tr
/\ exists (dfinal dfirst : MachineDescriptor),
equivocator_vlsm_trace_project _ btr dfinal = Some (tr, dfirst).```

2020-11-25 14:03 UTC, traiansf commented on VLSM/Equivocators/MessageProperties.v
> +      In item tr.
I'm not sure I follow what's your point here.  What difference does it make whether it is quantified or not? I agree that the latter hypotheses don't depend on them; however we prove them in the same fashion, and we destruct them similarly whether they are in a conjunction or an existential quantification (which I take to be a dependent conjunction).  Can you give me a good reason why my approach is problematic?

2020-11-25 20:51 UTC, bmmoore commented on VLSM/Equivocators/MessageProperties.v
> +      In item tr.
The problematic part is still using a dependent product when a non-dependent one will work.
The benefits are not so big or clear here, because there is enough real dependency that we can't avoid an `exists` at the top level.

Writing an unnecessary `exists` is a little bit misleading by suggesting that the body might depend on the parameter, similarly to writing `forall (a:A), ...` instead of `A -> ...`. (With the trouble we have with implicit parameters from class stuff, I still wonder if it might be used invisibly even if it is not mentioned explicitly).
This is less of a concern when we're already inside `exists item, _`, and have to understand that dependency.

It also affects some functionality. Tactics like `apply` and `tauto` can automatically take apart some products for you (that's why you can `apply` an `A <-> B` without explicitly `destruct`ing to get the direction you want).
With `exists` it can't find the body:

```
Lemma and1 A B (H: A /\ B) : A. Proof. apply H. Qed.
Lemma and2 A B (H: A /\ B) : B. Proof. apply H. Qed.
Lemma ex1 A B (H: exists (a:A), B) : A. Proof. apply H. Qed.
Lemma ex2 A B (H: exists (a:A), B) : B. Proof. try (apply H). Abort.
```

This is is also probably not so useful with the `exists` at the top level - those tactics can't get at the body without some manual de-structuring anyway, so we could just as well completely split up all the nested existentials.

2020-11-25 20:53 UTC, bmmoore approved these changes
Code looks good. Don't forget to remember to make a reminder to simplify the oversized proof.

2020-11-26 07:19 UTC, traiansf commented on VLSM/Equivocators/MessageProperties.v
> +      In item tr.
Thanks for the details. I'll definitely keep that in mind for future work. I was usually destructing products before applying them, so I failed to see the benefits before you mentioning it, but I'll definitely try it in my future proof scripts.

2020-11-26 08:25 UTC, traiansf commented on VLSM/Equivocators/MessageProperties.v
> +      In item tr.
I decided in the end to rewrite that lemma the way you proposed.

2020-11-26 08:40 UTC, merged