Refactored observation-based equivocation evidence
runtimeverification/casper-cbc-proofs pull request #156
Opened 2020-12-10 17:37 UTC by traiansf

- replaced `observable_events` which returned a set with an `has_been_observed` decidable predicate and a `subject_of_observation` partial map
- changed no_events_in_initial_state to state that events in initial state have no subject of observation
- replaced message_observable_events with the decidable predicate message_has_been_observed
- propagated changes to all modules using observable equivocation

Classes
- moved some generic stuff to Lib/Classes
- Defined dec_sig for sub types given by a decidable predicate, for which we can prove proof_irrelevance. 

Lists
- added Exists_first lemma

2020-12-10 23:13 UTC, bmmoore reviewed
I haven't finished reviewing the big changes under `VLSM/FullNode/` and in `ObservableEquivocation` and `PreceedsEquivocation`, the rest looks good and I have some suggestions for the lemmas in `Lib/Classes` and `Lib/ListExtras.v`

I'll finish reviewing the remaining files tomorrow.

2020-12-10 23:13 UTC, bmmoore commented on Lib/ListExtras.v
> +  elim Hnone_before. apply Exists_exists. exists x. intuition.
This can be a bit simpler by using `setoid_rewrite` to turn the `existsb` subterm into an `Exists` so we can conclude by applying the `Exists_first` lemma instead of needing to deconstruct the result.

2020-12-10 23:13 UTC, bmmoore commented on Lib/ListExtras.v
> +Qed.
Instead of doing the induction, this proof could use lemmas about `Exists` and `Forall` after `setoid_rewrite not_true_iff_false`.

2020-12-10 23:13 UTC, bmmoore commented on Lib/ListExtras.v
> +Qed.
Is there any reason to use `generalize_dependent l; induction l; intros.` instead of just `induction l.`? I think that's already how `induction` handles other hypotheses.
Also, `exists` can be used with multiple comma-separate arguments, if there are several.

For a slightly larger change, after `exists` removes the quantifiers, `rewrite` can be used immediately with `Exists_nil` and `Exists_cons` (in the two cases) to leave a conjunction that `tauto` can hangle.

2020-12-11 09:38 UTC, traiansf commented
@bmmoore  Thanks for the comments and for the fixes.

2020-12-14 06:35 UTC, bmmoore requested changes
I have some questions and suggestions about the design of the changed class in ObservableEquivocation.v, and also the `trace_generated_event` definition vs. documentation. There's also one proof in Free.v which is too big to cram into a `Next Obligation`.

Besides that there are local suggestions on proofs, plus some opportunities for extending Lib with some Decision lemmas/instances to help many of the `_dec` definitions.

2020-12-14 06:35 UTC, bmmoore commented on VLSM/FullNode/Client.v
> +    apply @Exists_dec.
Maybe we should have a lemma (or instance?) for this combination `Decision_iff (Exists_exists _ _) (Exists_dec _)`.

I tested that with

```
  Local Instance decision_Exists [A : Type] [P : A -> Prop] [l : list A]
    : (forall x, Decision (P x)) -> Decision (exists x, In x l /\ P x).
  Proof.
    intro H.
    exact (Decision_iff (Exists_exists _ _) (@Exists_dec _ _ H _)).
  Qed.
  Local Existing Instance Decision_and.

  Local Instance decide_nrel:
    forall {A B : Type} (R : A -> B -> Prop), RelDecision R ->
                                              forall (x : A) (y : B), Decision (~R x y).
```
everything after the `unfold` could be replaced by `exact (decide _)` (or `typeclasses eauto`).

If we don't want lemmas like `Decision_and` to be active as instances all the time, we could create a special HintDb that we will use when defining new `_dec` functions, and only register lemmas like `Decision_and` as Instances inside that HintDb.

2020-12-14 06:35 UTC, bmmoore commented on VLSM/FullNode/Composite/Free.v
> +Next Obligation.
Isn't this exactly the statement proved in `ObservableEquivocation.v`, in the instance of `EqDecision` for the `observable_events_equivocation_evidence` version of `equivocation_evidence`?

Even if not, it's the same sort of lemma that was a separate named definition in the other files in this PR, and it's complicated enough that splitting it out is the right thing to do.

2020-12-14 07:22 UTC, traiansf commented on VLSM/ObservableEquivocation.v
> +        ~ comparable happens_before e1 e2;
I'm not 100% sure about what the best way to specify this would be.  I think that we shouldn't be considering that the type of events is determined by the combination of state and validator.  I think It might be a good idea to extract the has_been_observed stuff as a separate class; this might allow us to have a similar treatment to the has_been_sent_capabilities later.

2020-12-14 08:37 UTC, traiansf commented on VLSM/ObservableEquivocation.v
> +  { firstorder. replace v with x; [assumption|]. apply observed_event_subject in H.
you are right here. stating it quantified over e allowed it to be directly used by firstorder to completely discharge the claim, without needing to apply it manually.

2020-12-14 18:13 UTC, bmmoore commented on VLSM/ObservableEquivocation.v
> +        ~ comparable happens_before e1 e2;
I'm thinking more of declaring a Mode, or changing the class design. Would we want inference to guess a value for `event` while searching for a class instance if you use `equivocation_evidence` (whose parameters only determine `state` and `validator`?)

2020-12-15 13:03 UTC, traiansf commented on VLSM/ObservableEquivocation.v
> +        ~ comparable happens_before e1 e2;
Actually Im not sure I would like that. Somehow, each type of event induces a particular type of equivocation_evidence, so searching for a suitable candidate might be problematic in this context.

2020-12-17 13:16 UTC, traiansf commented on VLSM/ObservableEquivocation.v
> +evidence of equivocation.
The original hypothesis was that there are no events observable in the initial state, and that's happening in all examples we have so far, but since Vlad seems to care a lot about this possibility, we adjusted it accordingly.

2020-12-17 13:17 UTC, traiansf commented on VLSM/ObservableEquivocation.v
> +    message_has_been_observed : message -> event -> Prop;
I've made this an instance of the has_been_observed

2020-12-17 13:18 UTC, traiansf commented on VLSM/ObservableEquivocation.v
> +  : RelDecision option_message_has_been_observed.
you are right. We also have something similar for option_protocol_message, although we don't have decidability there.

2020-12-17 13:24 UTC, traiansf commented on VLSM/ObservableEquivocation.v
> +  : RelDecision option_message_has_been_observed.
However, on a closer look, it's not always clear how the non-existence of the optional is interpreted. Sometimes it is as "True", and sometimes, like here, as "False"

2020-12-21 07:44 UTC, traiansf commented
@bmmoore I've tried to incorporate your comments, but that implied a lot of refactoring, too. Could you please take another look?  If there are still issues you'd like me to address, I'd prefer doing that in a separate PR.

2020-12-21 18:55 UTC, bmmoore approved these changes
The refactoring all is good. The remaining part of `observation_based_equivocation_evidence` looks a bit odd to me, but I don't have any good suggestions.

2020-12-22 12:23 UTC, merged