General-interest prep work for lv_common_futures.
runtimeverification/casper-cbc-proofs pull request #161
Opened 2020-12-16 10:42 UTC by mcalancea

This PR extracts some non-LV-specific definitions and results from the `lv_common_futures` branch.

2020-12-16 14:08 UTC, palmskog commented on Lib/ListExtras.v
> +  `{EqDecision A}
```suggestion
  `{EqDecision A}
```
The backtick makes the explicit `A` redundant.

2020-12-16 14:08 UTC, palmskog commented on Lib/ListExtras.v
> +  `{EqDecision A}
```suggestion
  `{EqDecision A}
```
Same as above.

2020-12-16 14:08 UTC, palmskog commented on Lib/ListExtras.v
> +  `{EqDecision A}
```suggestion
  `{EqDecision A}
```

2020-12-16 14:08 UTC, palmskog commented on Lib/ListExtras.v
> +  `{EqDecision A}
```suggestion
  `{EqDecision A}
```

2020-12-16 14:08 UTC, palmskog commented on Lib/ListExtras.v
> +  `{EqDecision A}
```suggestion
  `{EqDecision A}
```

2020-12-16 14:08 UTC, palmskog commented on Lib/ListExtras.v
> +  `{EqDecision A}
```suggestion
  `{EqDecision A}
```

2020-12-16 14:08 UTC, palmskog commented on Lib/ListExtras.v
> +  `{EqDecision A}
```suggestion
  `{EqDecision A}
```

2020-12-16 14:08 UTC, palmskog commented on Lib/ListSetExtras.v
> +  (preceeds : A -> A -> Prop)
```suggestion
Definition get_maximal_elements
  `(preceeds : A -> A -> Prop)
```

2020-12-16 14:08 UTC, palmskog commented on Lib/ListExtras.v
> +  (lf : list (A -> B))
I guess this is OK, but when do you usually have a list of functions like this? Wouldn't it make more sense to have a family of `A -> B` functions indexed by a `nat`, i.e., `f: nat -> A -> B`?

2020-12-16 15:41 UTC, palmskog approved these changes

2020-12-17 13:06 UTC, traiansf approved these changes
Looks good to me. In general I'd like to see a few more comments especially next to any definition/lemma with a longer statement and whose name does not fully convey the idea of what it stands for.

2020-12-17 13:06 UTC, traiansf commented on VLSM/Composition.v
> +  Lemma relevant_component_transition
Maybe document this a little/

2021-02-08 14:33 UTC, traiansf requested changes
Looks good, in general. I'd like to take another look on it though after you implement the suggested changes.

2021-02-08 14:33 UTC, traiansf commented on VLSM/Common.v
> +     Lemma protocol_message_from_protocol_trace_receive
We now have `protocol_trace_input_is_protocol` which state the same thing.

2021-02-08 14:33 UTC, traiansf commented on VLSM/Equivocation.v
> +    Lemma has_been_sent_initially_false
This can now be derived directly through the relation between has_been_send_capability and oracle_stepwise_props, using: `has_been_sent_stepwise_props`. Maybe move this lemma there.

2021-02-08 14:33 UTC, traiansf commented on VLSM/Equivocation.v
> +    Lemma has_been_received_initially_false
Same comment as above.

2021-02-08 14:33 UTC, traiansf commented on VLSM/Equivocation.v
> +  Lemma sent_component_protocol_composed
You can now prove this easier by using that the `has_been_sent_capability` instance for the composition and that `has_been_sent` for the composition is implied by `has_been_sent` for a component, then applying `proper_sent` on it, using `protocol_state_has_trace` to get a witness trace and `protocol_trace_output_is_protocol`.

2021-02-08 14:33 UTC, traiansf commented on VLSM/Equivocation.v
> +  Lemma received_component_protocol_composed
same as above

2021-02-09 13:57 UTC, traiansf approved these changes

2021-02-09 13:57 UTC, traiansf commented on Lib/ListExtras.v
> +Example cat_option1 : cat_option [Some 1; Some 5; None; Some 6; None] = [1; 5; 6].
Nice :-)

2021-02-09 13:57 UTC, traiansf commented on VLSM/Equivocation.v
> +      (* There's probably a shortcut for this, but where is it? *)
Actually, there isn't one... yet.  
It's coming as part of my PR under review: https://github.com/runtimeverification/casper-cbc-proofs/pull/172/files#diff-943fd6a420d34fd491db0bceef5c37ed734d33040f5ba0436a881b1e8b024299R2269

2021-02-09 14:57 UTC, merged