Fixed set equivocation proof
runtimeverification/casper-cbc-proofs pull request #179
Opened 2021-02-25 13:29 UTC by traiansf

2021-03-09 22:55 UTC, bmmoore requested changes
Most of the code looks good. Changes I've requested are mostly about adding more explanation to definitions.

For long proofs a few inline comments labeling parts of the proof might make it easier to see the argument structure without needing to step through all the proof details.

2021-03-09 22:55 UTC, bmmoore commented on VLSM/Equivocators/Composition/Projections.v
> +Lemma equivocators_trace_project_app_inv_item
I think it would be easier to prove `equivocators_trace_project_app_inv` first, and use it as a lemma to prove `equivocators_trace_project_app_inv_item`. Maybe also with a lemma for the singleton case `equivocators_trace_project _ _ = Some ([item], _)`.

2021-03-09 22:55 UTC, bmmoore commented on VLSM/Equivocators/Composition/Projections.v
> +    { clear - Hproject_x Hproject_sub_x.
This looks like a very long argument to have inside brackets after an `assert`. Pulling it out as a separate lemma should make the proof clearer.

2021-03-11 12:50 UTC, traiansf commented on VLSM/Common.v
> +      : in_futures X s1 s2 -> in_futures Y s1 s2.
Actually, in practice, this form seems to help inferring the `X` machine. Maybe what helps is not actually writing it in this form, but the fact that I use a revert to set the goal in this form, but I would still like to keep the same form in both places.

2021-03-11 18:56 UTC, bmmoore commented on VLSM/Common.v
> +      : in_futures X s1 s2 -> in_futures Y s1 s2.
The important part is actually putting the goal into that form. I had some wrong ideas about how `apply` handles goals with visible implications, but was correct that these two ways of writing the signature don't change how apply uses it. I agree this form looks nicer for people.

Checking the implementation of apply (starting at `let apply c =` in `tactics/tactics.ml`, main logic in `general_apply`), it mostly only cares about the number of arguments expected by the term to be applied, and the number of implications in the goal, and it counts them in a way that doesn't distinguish a named `forall` from `->`, or where the `:` was.
When a goal has visible implications, `apply` passes that many fewer arguments to the term. (If trying to resolve the goal with an application of `term` fails, it falls back to checking if the term is (or returns) something like a conjunction that it can try to decompose and apply components of).

So, after reverting your `in_futures X s1 s2` hypothesis, `apply VLSM_incl_in_futures` will try something like `refine (VLSM_incl_in_futures _ _ _ _ _)` - passing wildcards for only up through `s2`, and unifying the whole `in_futures X s1 s2 -> in_futures Y s1 s2` part against the goal. This should reliably fill in X. (unless your `X` can't be put in the form `mk_vlsm _` - I think I've run into problems because of that when I have an argument or section variable like `(X : VLSM message)`).

2021-03-15 14:30 UTC, traiansf commented on VLSM/Equivocators/Composition/Projections.v
> +      (equivocators_vlsm_transition_item_project_zero_descriptor (IM (projT1 (l item)))
It might be. However, this allows for more flexibility as it lets me use it with any composition, whatever the constraint might be.

Using protocol_transition while keeping the same generality would ask for `pre_loaded_with_all_messages_vlsm (free_composite_vlsm equivocator_IM)` as the VLSM for protocol_transition, which would require going through some `VLSM_incl` lemmas to be able to apply it instead of simply destructing a protocol transition as I do now.

2021-03-15 16:33 UTC, bmmoore commented on VLSM/Equivocators/Composition/Projections.v
> +      (equivocators_vlsm_transition_item_project_zero_descriptor (IM (projT1 (l item)))
Ah, I thought this was hardcoding the validity condition of a particular VLSM, but this looks good if `composite_valid` is expected to be only part of the validity condition, and you expect to use this by destructuring a `protocol_transition` to throw away the validity constraint.

2021-03-18 06:48 UTC, traiansf commented on VLSM/Equivocators/Composition/LimitedEquivocation/FixedEquivocation.v
> +  subst lst_trX.
I extracted a separate lemma proving the has_been_observed.  You are right, it was more than just an elim, and it deserved its own result.

2021-03-18 06:49 UTC, traiansf commented on VLSM/Equivocators/Composition/LimitedEquivocation/FixedEquivocation.v
> +  inversion Hpt. subst. clear Hpt.
There is indeed such a lemma. Thanks for pointing it out.  It makes things much cleaner.

2021-03-18 07:29 UTC, traiansf commented on VLSM/Equivocators/Composition/LimitedEquivocation/FixedEquivocation.v
> +  - simpl in Hlst. subst s. destruct Htr as [_ His].
nice. thanks for pointing it out!

2021-03-18 07:33 UTC, traiansf commented on VLSM/Equivocators/Common.v
> +  destruct (le_lt_dec (S (projT1 s)) ei); [lia|].
well, at the moment the lemmas you see in `VLSM.Equivocators.Common` are providing this functionality, which is a progress. I'll add a TODO for thinking about improving them even further as you mention.

2021-03-18 13:21 UTC, traiansf commented on VLSM/Equivocation.v
>    Definition full_node_condition_for_admissible_equivocators
> Maybe there is an even more general lemma for `cannot_resent_messges_stepwise_prop` VLSM saying that for those VLSMs a no equivocations constraint is equivalent to single-state test about messages that are `has_been_received` and `has_not_been_sent`.

I have extracted some lemmas; however, I was not sure about your quoted comment, as no_equivocation s m is already expressed as has_been_sent s m

However, while trying to interpret what you meant, I got to an interesting result:
if `valid` implies `no_equivocations` (as in your `NoEquivocationInvariants` section) then the VLSM is trace-equal to its `pre_loaded_with_all_messages_vlsm` version.  I guess that could be read as `no_equivocations` is a validating condition

2021-03-19 19:01 UTC, bmmoore commented on VLSM/Common.v
> +      replace (Some m) with (output x) by assumption.
The problem has been tracked down a certain Instance, which has been removed in #185. I still don't understand why it causes this problem.

2021-03-19 19:19 UTC, bmmoore commented on VLSM/Equivocation.v
>    Definition full_node_condition_for_admissible_equivocators
I wasn't thinking of just one message `m`. I mean that if a VLSM satisfies `cannot_resend_messages_stepwise_prop`, then on any initial trace to a state `s` that satisfies `forall m, has_been_received s m -> has_been_sent s m`, there cannot have been any equivocation along the trace, because the history of an out-of-thin air receive can't be concealed by later resending it.

This shouldn't depend on `valid` already implying `no_equivocations`. But I don't know a very good way to state it - I was thinking in terms of taking the VLSM, modifying it to add a `no_equivocations` constraint to `valid`, and claiming that we can only lose a finite trace if it ends in a state failing that `forall m, has_been_received s m -> has_been_send s m` test.

I don't think we have a definition for taking a single VLSM and building one with a stronger constraint (just definitions for building a composite VLSM that adds a composition constraint along with taking the product - perhaps we should refactor some VLSM-building definitions), so that way of expressing it would be awkward.

2021-03-19 20:03 UTC, bmmoore approved these changes
Looks good, except you added a few trailing whitespace while fixing previous concerns.

2021-03-22 10:01 UTC, merged