FullNode Validator has_been_sent/received stepwise.
runtimeverification/casper-cbc-proofs pull request #180
Opened 2021-03-01 13:04 UTC by mcalancea

Refactor has_been_sent/received for FullNode Validator with stepwise props.

2021-03-01 16:20 UTC, bmmoore requested changes
Looks good besides naming.

2021-03-01 16:20 UTC, bmmoore commented on VLSM/FullNode/Validator.v
> +  Definition send_oracle
I think we should the convention used in other instances (both defining has_been_sent_capability and other classes) and name this underlying implementation something specific to this instance, like `VLSM_full_validator_has_been_sent`. The name `send_oracle` could apply to any VLSM, and will be in scope wherever this module is imported.

2021-03-01 16:20 UTC, bmmoore commented on VLSM/FullNode/Validator.v
> +  Definition receive_oracle
Likewise for the name of the received predicate.

2021-03-02 08:07 UTC, traiansf approved these changes
please remove spaces from end of line.

2021-03-02 18:32 UTC, bmmoore approved these changes
Looks good

2021-03-04 08:26 UTC, merged