Dependent messsages and full-node condition
runtimeverification/casper-cbc-proofs pull request #191
Opened 2021-03-25 15:25 UTC by traiansf

2021-06-07 13:10 UTC, palmskog commented on VLSM/Equivocators/Composition/Common.v
> +Defined.
I think it also makes sense to turn `equivocator_Hbs` from a "lemma" to a "definition", i.e., change to:
```coq
Definition equivocator_Hbs
  (i : index)
  :  has_been_sent_capability (equivocator_IM i).
```
This is because `has_been_sent_capability` lives in `Type` and not `Prop`. The convention in Coq is to have the former use `Definition` and the latter use `Lemma`.

2021-06-09 14:07 UTC, traiansf commented on VLSM/DependentMessages.v
> +Class DependentMessages
rename to `MessageDependencies`

2021-06-09 14:14 UTC, traiansf commented on VLSM/DependentMessages.v
> +        @state_received_not_sent _ (IM (A v)) (Hbs (A v)) (Hbr (A v)) s dm
change to `has_been_observed`

2021-06-09 15:34 UTC, traiansf commented on VLSM/Equivocators/Composition/Common.v
> +Defined.
Thanks!

2021-07-01 11:48 UTC, palmskog approved these changes
This is a big PR which cuts across a large part of the whole project, which is why I think we should try to merge it as soon as possible.

I fixed the most glaring documentation and formatting issues in a small commit, and now everything looks good to me from a general Coq perspective. Would be good if we can get "content approval" from @bmmoore as well.

2021-07-01 11:48 UTC, palmskog commented on VLSM/MessageDependencies.v
> +*)
Do we need to keep this comment? I fear it may be confusing in the future. If you want to keep it, maybe we can prefix by saying something like:
> An alternative definition that was rejected because of X.

2021-07-20 15:09 UTC, palmskog commented on VLSM/Equivocators/Composition/LimitedEquivocation/LimitedEquivocation.v
> +  message_dependencies_local_full_node_constraint (@existT _ _ i li) (sX', Some input).
```suggestion
  message_dependencies_local_full_node_constraint (existT i li) (sX', Some input).
```

2021-07-20 15:09 UTC, palmskog commented on VLSM/Equivocators/Composition/LimitedEquivocation/LimitedEquivocation.v
> +       (@existT _ (fun n : index => vlabel (IM n)) (projT1 l) (fst (projT2 l)))
```suggestion
       (existT (projT1 l) (fst (projT2 l)))
```

2021-07-20 15:09 UTC, palmskog commented on VLSM/Equivocators/Composition/Projections.v
> +        (lx : composite_label IM :=  @existT _ (fun i => vlabel (IM i)) (projT1 (l item)) (fst (projT2 (l item))))
```suggestion
        (lx : composite_label IM := existT (projT1 (l item)) (fst (projT2 (l item))))
```

2021-08-02 13:07 UTC, bmmoore requested changes
I've suggested many little changes.

The significant design questions are how message dependencies are expressed, and the weakening of `not_equivocating_equivocator_descriptor` used in the big lemma.

I made a PR into this branch that simplifies the structure of the main `_equivocators_trace_project` theorem, and has some other changes as well. It doesn't include everything I suggested as a comment, nor do I have a comment here for all its changes.

I have many little suggestions, but it looks ok to merge once you've seen them. (The message dependencies class seems incomplete, but nothing is relying on that part so we don't need a complete design yet).

2021-08-03 06:48 UTC, traiansf commented on VLSM/Equivocators/Composition/LimitedEquivocation/LimitedEquivocation.v
> +Lemma equivocators_transition_preserves_equivocating_indices_and_newmachines
I think we can remove it for now.

2021-08-03 10:16 UTC, traiansf commented on VLSM/Equivocators/Composition/LimitedEquivocation/LimitedEquivocation.v
> +    (Hitem_project: equivocators_transition_item_project IM s1_descriptors item = Some (Some itemX, s_descriptors)),
Once I introduced a definition as you suggested, I was able to prove the non-heaviness result as has_non_equivocating_descriptors_suffix_not_heavy

2021-08-03 11:35 UTC, traiansf commented on VLSM/Equivocators/Common.v
> +  | Existing _ i _ => i < S (projT1 s)
I think this is because we use of_nat_lt, so having < is better than <=

2021-08-03 14:13 UTC, traiansf commented on VLSM/Equivocation.v
> +    (globally_known_equivocators : composite_state IM -> set validator)
I totally rewrote this in the next PR, so I would postpone addressing this issue for next time.

2021-08-03 14:14 UTC, traiansf commented on VLSM/Equivocation.v
> +    can_emit (pre_loaded_with_all_messages_vlsm (IM i)) m /\
It actually is important. Otherwise I would need to work with validating components which would make the two equal.

2021-08-03 14:16 UTC, traiansf commented on VLSM/Equivocation.v
> +  Global Instance free_composite_has_been_sent_capability : has_been_sent_capability Free :=
The instance wasn't picked up automatically. But also I realized that we only ever use the composite capability for the free composition.

2021-08-03 14:18 UTC, traiansf commented on VLSM/Composition.v
> +Lemma can_emit_composite_free_project
I don't remember whether it's still necessary; however I would leave it it as it seems pretty clear and clean.

2021-08-03 19:57 UTC, bmmoore commented on VLSM/Equivocators/Common.v
> +  | Existing _ i _ => i < S (projT1 s)
Ok, that makes sense unless we can get rid of `Fin.t`. And even switching the equivocator state to `list (vstate X)` instead of a dependent pair of nat and vec might not get rid of it - when I made a quick look at starting to redefine the state, there were still a number of lemmas and functions that want to know an index is valid, meaning taking either `Fin.t` or multiple arguments for a number and an inequality proof. But on the other hand I think we should probably have at least our own named definition for "valid index into this state", even if the body of the definition just uses `Fin.t`, and supply our own special purpose lemmas for things like saying that a nat which is a valid index into a state is also a valid index in the extension of the state, and such lemmas could easily do stuff like proving `n < S m` from `n <= m` if necessary. Anyway, this is all out of scope for this PR.

2021-08-03 20:20 UTC, bmmoore approved these changes
Looks good.

I think there is probably more room to clean up the proof of the main theorem, but all the big concerns are addressed, and no reason not to commit this.
(one possibility, now that `has_not_equivocating_descriptors_suffix` is a named definition, maybe more of the work to prove the arguments of the induction hypothesis could be extracted as nicely stated lemmas).

2021-08-03 20:20 UTC, bmmoore commented on VLSM/Equivocators/Composition/LimitedEquivocation/LimitedEquivocation.v
> +    (Hitem_project: equivocators_transition_item_project IM s1_descriptors item = Some (Some itemX, s_descriptors)),
I don't know if it's useful, but I also conjectured that the reverse direction holds:
```forall
  (final_descriptors : equivocator_descriptors IM)
  (final_state : composite_state (equivocator_IM IM)),

   (sum_weights
     (set_union IndEqDec
        (equivocating_indices IM index_listing final_state)
        (newmachine_descriptors_list IM index_listing
          final_descriptors)) <= ` threshold)%R
  -> has_non_equivocating_descriptors_suffix final_descriptors final_state
```

2021-08-03 20:28 UTC, merged