An alternate definition for validating (from VLSM2 paper)
runtimeverification/casper-cbc-proofs pull request #202
Opened 2021-05-13 10:42 UTC by traiansf

The component $X_i$ is {\bf validating for $k$} if validity of a (label $l$, prestate $s$, optional premessage $m$) triple in $X_i$ such that $s\in \S_{Proj_i}$ implies that there exists a state $s'$ whose $i$th component is $s$, $s'$ and $m$ are protocol in $X$, and $(j, l) \valid (s', m)$ in $X$.

In our formulation, 1there exists a state $s'$ whose $i$th component is $s$, $s'$ and $m$ are protocol in $X$, and $(j, l) \valid (s', m)$ in $X$` is replaced by `$l \valid_{Proj_j} (s,m)$` which basically says the same thing.

2021-06-09 23:47 UTC, bmmoore requested changes
Maybe I'm looking at an outdated printout of the VLSM2 paper, but I don't see how the `validating_projection_prop_alt` corresponds to the text in the paper, or to the text in the PR description.

Aside from that, the proof structure can be simplified, as described in comments on the code. The big thing is that the induction over a `protocol_state_prop` assumption in the main theorem is proving a more complicated statement that needed.

2021-06-09 23:47 UTC, bmmoore commented on VLSM/Validating.v
> +      cut (protocol_state_prop Xi si /\ vvalid Xi l (si, om)).
Yes, that actually works out.

```
Lemma validating_alt_free_states_are_projection_states
    : validating_projection_prop_alt ->
    forall s,
        protocol_state_prop (pre_loaded_with_all_messages_vlsm (IM i)) s ->
        protocol_state_prop Xi s.
Proof.
    intros Hvalidating s Hs.
    induction Hs using protocol_state_prop_ind;
    [apply initial_is_protocol;assumption|].
    change s' with (fst (s',om')).
    destruct Ht as [[_ [_ Hvalid]] Htrans].
    rewrite <- Htrans.
    apply (projection_valid_implies_protocol_state IM constraint i).
    apply (Hvalidating l (s,om));assumption.
Qed.
```

and then the forward direction of this proof is just

```
    - intros Hvalidating l (si, om) Hvalid.
      destruct Hvalid as [Hsi [_ Hvalid]].
      assert (protocol_state_prop Xi si) as Hsi'
        by (apply validating_alt_free_states_are_projection_states;assumption).
      exact (Hvalidating l (si,om) Hvalid Hsi').
```

2021-06-09 23:47 UTC, bmmoore commented on VLSM/Validating.v
> +(** An seemingly stronger alternative formulation of the above property,
Is this a "stronger formulation"? I think the `protocol_state_prop Xi si` is a stronger assumption, making `validating_projection_prop_alt` (apparently) weaker overall.

2021-06-16 06:03 UTC, traiansf commented
> Maybe I'm looking at an outdated printout of the VLSM2 paper, but I don't see how the `validating_projection_prop_alt` corresponds to the text in the paper, or to the text in the PR description.
> 

The text in the PR corresponds to the one in the VLSM2 paper.
![image](https://user-images.githubusercontent.com/2890067/122165804-67a67f80-ce81-11eb-8089-dfa096996ab6.png)

As to why `validating_projection_prop_alt` corresponds to them, it's due to the fact that validity for the projection is defined as the existence of a protocol state projecting to the state component and protocol message in the composition such that validity os lifted, which is basically the conclusion of the definition.

2021-06-16 06:12 UTC, traiansf commented on VLSM/Composition.v
> +    Lemma projection_valid_preserves_protocol_state
Note that we already have a `protocol_state_projection` lemma here: https://github.com/runtimeverification/casper-cbc-proofs/blob/master/VLSM/ProjectionTraces.v#L297
I would rather keep this lemma as is here, and maybe add another lemma in `ProjectionTraces` which removes the extra assumption. Would that be acceptable?

2021-06-16 06:20 UTC, traiansf commented on VLSM/Validating.v
> +(** An seemingly stronger alternative formulation of the above property,
you're right.  I meant a formulation with a stronger assumption. Indeed, it's (seemingly) a weaker assumption overall.

2021-06-16 06:37 UTC, traiansf commented on VLSM/Validating.v
> +      cut (protocol_state_prop Xi si /\ vvalid Xi l (si, om)).
Thanks for pointing that out. I had it implied in the comment, but extracting it as a separate lemma is definitely the better choice.

2021-06-16 15:02 UTC, bmmoore commented on VLSM/Composition.v
> +    Lemma projection_valid_preserves_protocol_state
I think the result makes more sense in `Composition`, next to `protocol_message_projection`. It seems the only reason to put it in `ProjectionTraces` is because your proof uses some results from there, but the proof I wrote above doesn't need them. It is a bit longer, but if you consider that the lemma that was depending on `projection_valid_preserves_protocol_state` had to do extra work to provide the hypothesis, I don't think it even costs code size overall.

2021-06-16 15:05 UTC, bmmoore requested changes
I think `protocol_state_prop` should be in `Composition`, and used right away rather than having the extra hypothesis on `projection_valid_preserves_state_prop` (which would also need to be renamed). (Probably this also lets you remove the other added lemmas in `ProjectionTraces`, or maybe move what is kept into `Composition`).

Otherwise it looks good.

2021-06-17 02:32 UTC, bmmoore approved these changes
Looks good

2021-06-17 02:33 UTC, merged