Fixed limited
runtimeverification/casper-cbc-proofs pull request #210
Opened 2021-07-14 08:42 UTC by traiansf

This should be merged after PR #191 and after or instead of PR #206

2021-08-16 15:04 UTC, palmskog reviewed
The pure Coq and documentation side looks reasonable, with some minor comments and suggestions from me. However, I think we need @bmmoore to comment on the content a bit before merging.

2021-08-31 21:10 UTC, bmmoore requested changes
Looks pretty good. Some comments need to be added or updated. I think the design seems fine but had some big picture questions about the design, some of which should probably be covered by comments in the code rather than just replied to here.

I put little fixes and improvements in PR #217.

I'm requesting the documentation changes, suggestions on definitions are not critical (we can remove basic_equivocation later).

2021-09-01 12:11 UTC, traiansf commented on VLSM/Equivocation/NoEquivocation.v
> +  (** It is now straightforward to define a [no_equivocations] composition constraint.
Thanks. It was extracted from the Equivocation file where there was some context about it, but I forgot to update the comments.

2021-09-02 08:55 UTC, traiansf commented on VLSM/Equivocation/NoEquivocation.v
> +Definition composite_no_equivocations_except_from
I actually think this is might be a good idea, having encountered myself several times similar issues, including one in which I wanted to strengthen the validity of a single VLSM.  But yes, it seems that doing that might require all kind of commutation lemmas with all the other operations we have on VLSMs.

2021-09-02 08:57 UTC, traiansf commented on VLSM/Equivocation/NoEquivocation.v
> +Section CompositeNoEquivocationInvariants.
it seems you've already did that :-)

2021-09-02 12:50 UTC, traiansf commented on VLSM/Equivocators/Composition/Projections.v
> +  (Htr : finite_protocol_trace_init_to PreFreeE is final_state tr)
I'm not sure I get it. The next lemma uses this one in its proof. would you redo the proof?

2021-09-02 13:28 UTC, bmmoore commented on VLSM/Equivocators/Composition/Projections.v
> +  (Htr : finite_protocol_trace_init_to PreFreeE is final_state tr)
It should be an easy modification of the proof you have for the first lemma, just removing the bits that handle the initial_state_prop part of finite_protocol_trace_init_to. Then the finite_protocol_trace_init_to lemma would be an easy corollary of the finite_protocol_trace_from_to lemma - it's much easier to use a lemma about finite_protocol_trace_from_to to help prove something about finite_protocol_trace_init_to by just using it on the trace part, than it is to somehow come up with an initial state to appeal to a lemma about finite_protocol_trace_init_to as part of proving something for arbitrary finite_protocol_trace_from_to.

2021-09-06 07:08 UTC, traiansf commented on VLSM/Equivocators/Projections.v
> +*)
I added more comments and moved the original_descriptor as the first argument.

2021-09-06 08:06 UTC, traiansf commented on VLSM/Equivocation/TraceWiseEquivocation.v
> +    which does not verify the order in which receiving and sending occurred.
I agree, in general. However, in the setting I'm trying to create for the next PR, I'm hoping to show that for each protocol state there exists a special trace for which the is_equivocating_tracewise property is monotone: https://github.com/runtimeverification/casper-cbc-proofs/blob/60a02d6ea0bbcb3f687c15d4f8c165369b4c0c6e/VLSM/Equivocation/WitnessedEquivocation.v#L277

It's possible that more constraints will be required for that lemma to hold, but I think that there a result like that can be obtained.  That is the trace that I would then want to show it's also a trace for the composition with a fixed-set of equivocators (where the fixed set is chosen to  be the known equivocators of that state/trace).

Hence, the correspondence between limited equivocation and fixed-set equivocation would be a little weaker in one direction, but still take protocol states to protocol states, and selected protocol traces to protocol traces.

2021-09-06 08:27 UTC, traiansf commented on VLSM/Equivocators/Composition/Projections.v
> +  (Htr : finite_protocol_trace_init_to PreFreeE is final_state tr)
Hm... usually the tricky part that it's avoided by using `finite_protocol_trace_init_to` is that of proving that the "from" state of the trace is protocol (which is needed when the trace is empty). Instead one is left with the (usually easier task) of proving that the "init" state is initial.  I assume this case is similar. However, I wonder whether it would be possible to prove a generic result deriving the second result from the first...

2021-09-06 14:35 UTC, bmmoore commented on VLSM/Equivocation/TraceWiseEquivocation.v
> +    which does not verify the order in which receiving and sending occurred.
I haven't though much about choosing a history. I'll have to see the argument that you can construct a trace - the definition of tracewise equivocation means that if a step from s to s' was non-monotonic for `v` then there is some alternative history of `s'` where `v` didn't equivocate, but there is no immediate guarantee that the alternate trace doesn't show non-monotonicity for some other validator `v'` (even if the original trace was monotonic for `v'`). If we can produce such a trace, it seems likely that we can get a limited and fixed set equivocation lemma that lifts monotonic traces.

2021-09-06 15:01 UTC, bmmoore commented on VLSM/Equivocators/Composition/Projections.v
> +  (Htr : finite_protocol_trace_init_to PreFreeE is final_state tr)
Ok, I wasn't thinking about needing `protocol_state_prop`. Maybe that makes this the easiest way. But don't we already have some lemmas about protocol_state_prop of a projection? Perhaps not, I was looking and found only ones for single equivocator_vlsm machines rather than a composition, like `preloaded_equivocator_state_protocol_project`.

2021-09-13 10:48 UTC, bmmoore approved these changes
Looks good.
This covers the comments and code changes I wanted in this PR.

(The commit I added just fixes one misspelled word in a comment).

2021-09-13 12:51 UTC, merged