VLSM Projections 2
runtimeverification/casper-cbc-proofs pull request #220
Opened 2021-09-14 10:29 UTC by traiansf

Defined generalized VLSM projections and showed that several important relations between VLSMs are indeed projections.

This is a manually rebased version of PR #219

2021-09-15 07:55 UTC, palmskog approved these changes
Looks reasonable, but hard to comment on semantics at a high level.

2021-09-15 07:55 UTC, palmskog commented on VLSM/ByzantineTraces.v
> +From CasperCBC Require Import Lib.Preamble VLSM.Common VLSMProjections VLSM.Composition VLSM.ProjectionTraces VLSM.Validating.
```suggestion
From CasperCBC Require Import Lib.Preamble VLSM.Common VLSM.VLSMProjections VLSM.Composition VLSM.ProjectionTraces VLSM.Validating.
```
Since there are files with same name, let's try to always prefix modules with the local path (also in other files).

2021-09-15 07:55 UTC, palmskog commented on VLSM/Composition.v
> +      intros.  exists j, (exist _ _ H); reflexivity.
```suggestion
      ; [intros|assumption].
      exists j, (exist _ _ H); reflexivity.
```
Small refactoring to get closer to the general rule of thumb to have one sentence per line.

2021-09-15 07:55 UTC, palmskog commented on VLSM/Equivocators/Common.v
> +Lemma not_equivocating_descriptor_dec : RelDecision not_equivocating_descriptor.
```suggestion
Local Instance not_equivocating_descriptor_dec : RelDecision not_equivocating_descriptor.
```
To at least get local benefits from the typeclass machinery, if someone edits this file again. We should all try to use the generic `decide P` whenever we can.

2021-09-15 07:55 UTC, palmskog commented on VLSM/Equivocators/Composition/Common.v
> +Lemma not_equivocating_equivocator_descriptors_dec
```suggestion
Local Instance not_equivocating_equivocator_descriptors_dec
```
Same as above.

2021-09-15 07:55 UTC, palmskog commented on VLSM/Equivocators/Composition/LimitedEquivocation/LimitedEquivocation.v
> +    ) as Hproper.
```suggestion
    (preloaded_equivocators_protocol_trace_project_proper_initial IM s suf) 
    as Hproper.
```
Why break the parentheses to a separate line?

2021-09-15 07:55 UTC, palmskog commented on VLSM/Equivocators/Composition/LimitedEquivocation/LimitedEquivocation.v
> +     ) as Hsim.
```suggestion
       sX trX (equivocators_state_project IM (zero_descriptor IM) sX) (equivocators_total_trace_project IM trX))
      as Hsim.
```
Increases readability a bit.

2021-09-15 07:55 UTC, palmskog commented on VLSM/ProjectionTraces.v
> +Let us fix an indexed set of VLSMs <<IM>> and their composition <<X>> using <<constraint>>.
Can you maybe say something about the *goal* of this module/file before getting in to "Let us fix ..."? For example, a sentence summarizing what you are defining and proving.

2021-09-15 07:55 UTC, palmskog commented on VLSM/ProjectionTraces.v
> +(** ** Composite VLSM projections
```suggestion
(** * Composite VLSM projections
```
This should be a top-level header, *or* it should stay as-is and there should be a top-level header above it.

2021-09-15 07:55 UTC, palmskog commented on VLSM/ProjectionTraces.v
> +Lemma preloaded_component_projection : VLSM_projection (pre_loaded_with_all_messages_vlsm X) (pre_loaded_with_all_messages_vlsm (IM j)) (fun s => s j) finite_trace_projection_list.
```suggestion
Lemma preloaded_component_projection : VLSM_projection (pre_loaded_with_all_messages_vlsm X)
 (pre_loaded_with_all_messages_vlsm (IM j)) (fun s => s j) finite_trace_projection_list.
```
Let's try to not have too long lines.

2021-09-15 07:55 UTC, palmskog commented on VLSM/VLSMProjections.v
> +*)
```suggestion
(** * VLSM (partial) projections and inclusions *)
```
One-liner is more readable.

2021-09-15 07:55 UTC, palmskog commented on VLSM/VLSMProjections.v
> +** VLSM partial projections
```suggestion
(** ** VLSM partial projections
```

2021-09-15 10:03 UTC, traiansf commented on VLSM/Composition.v
> +      intros.  exists j, (exist _ _ H); reflexivity.
Why is it better to have only one sentence per line?

2021-09-15 10:11 UTC, traiansf commented on VLSM/Equivocators/Composition/LimitedEquivocation/LimitedEquivocation.v
> +    ) as Hproper.
I have this (perhaps bad) habit of trying to match indentation between open an closed brackets.

2021-09-15 10:33 UTC, palmskog commented on VLSM/Composition.v
> +      intros.  exists j, (exist _ _ H); reflexivity.
Most people use shortcuts to step between sentences, and it helps significantly to get visual feedback on a sentence step if we also step between. If you have a line with 12 sentences, it gets really hairy to track where you are.

Also example of one big project where they use this convention: https://github.com/math-comp/math-comp/blob/master/mathcomp/ssreflect/fingraph.v

2021-09-15 17:03 UTC, bmmoore requested changes
There's a typo, some extra requested documentation, and changing how some implicit arguments are declared can let you avoid some of the proof changes.
(I think the proofs are mostly clearer the new way, but it's not good if somebody trying the old way would see mysterious failures. OTOH, using `apply` with a lemma about VLSM_incl without explicitly specifying the other VLSM was sometimes succeeding only by seeing if the starting state of a finite_protocol_trace/finite_protocol_trace_from was of the form `vstate X`)

2021-09-15 17:03 UTC, bmmoore commented on VLSM/VLSMProjections.v
> +  (Hincl : VLSM_incl X Y)
It might be better to use `VLSM_incl_part MX MY`. Not sure, but I think this has something to do with sometimes seeing types like `machine (mk_vlsm (....))` in the subgoals resulting from using these lemmas.

2021-09-16 06:25 UTC, traiansf commented on VLSM/VLSMProjections.v
> +  destruct Htr'X as [isX [preX [Htr'X HsX]]].
That's good to know. Thanks!

2021-09-16 14:21 UTC, traiansf commented on VLSM/VLSMProjections.v
> +
I started thinking about this and it indeed would make a lot of sense as we would eliminate some of the duplication needed to adapt `VLSM_partial_projection` to equivocator context.

However, I'd rather do this as part of a separate PR.

2021-09-16 14:24 UTC, traiansf commented on VLSM/Equivocators/Composition/Common.v
> +  : VLSM_incl (pre_loaded_with_all_messages_vlsm equivocators_no_equivocations_vlsm) (pre_loaded_with_all_messages_vlsm equivocators_free_vlsm).
I think we can define a notion of strong basic vlsm inclusion/ full projection which has a stronger correspondence between initial messages, valid, and transitions, and use that to derive VLSM_incl / VLSM_full_projection for both the normal VLSM and their pre-loaded versions. Maybe in some future PR.

2021-09-16 15:47 UTC, bmmoore approved these changes
Looks good

2021-09-16 15:51 UTC, merged