Witnessed equivocation and fixed-set equivocation
runtimeverification/casper-cbc-proofs pull request #221
Opened 2021-09-15 13:32 UTC by traiansf

2021-11-02 08:55 UTC, palmskog requested changes
This looks good in general from a Coq proof engineering and documentation view, but with some small things that need to be fixed.

For the overall "semantic" view, I have to trust that this is a good idea, so I will approve once the comments are addressed.

2021-11-02 08:55 UTC, palmskog commented on CBC/Protocol.v
> +Lemma sigify_eq_dec {X : Type} `{StrictlyComparable X} :
Is there an obvious reason why the `EqDecision` typeclass notation is not used here? It should give exactly the same term as this one when `Decision` is unfolded, but we actually record the instance.

2021-11-02 08:55 UTC, palmskog commented on VLSM/Composition.v
> +    Definition option_composite_initial_message_prop (om : option message) : Prop
This definition is so trivial that there should be some stdpp equivalent for it already. Maybe you can take a look in `stdpp/option.v` if something fits? I'd rather have fewer definitions even if this leads to a small measure more complicated expressions in other code.

2021-11-02 08:55 UTC, palmskog commented on VLSM/Equivocation/FixedSetEquivocation.v
> +(** ** A (semeingly) stronger definition for fixed-set equivocation
```suggestion
(** ** A (seemingly) stronger definition for fixed-set equivocation
```

2021-11-02 08:55 UTC, palmskog commented on VLSM/Equivocation/TraceWiseEquivocation.v
> +  match oim with
Here I also feel there should be something in `stdpp/option.v` to make this a bit shorter.

2021-11-02 08:55 UTC, palmskog commented on VLSM/Equivocation/WitnessedEquivocation.v
> +(** Main result of the section. Any Free protocol trace with the
Maybe use a coqdoc subsection here, such as:
````
(** *** Main result of the section

Other stuff goes here ...
*)
```

2021-11-02 08:55 UTC, palmskog commented on VLSM/SubProjectionTraces.v
> +Lemma i0 : Inhabited index.
If this is to be a globally accessible lemma, please use a better, more descriptive name than `i0`.

2021-11-08 04:11 UTC, bmmoore requested changes
A few typos and requests for clarification, but the main results and also the `protocol_prop` refactoring look good.

2021-11-08 04:11 UTC, bmmoore commented on VLSM/Equivocation/WitnessedEquivocation.v
> +are  included in the [equivocating_validators] for the source of its last
Isn't it impossible for this to be a strict inclusion, by the previous lemma? It's not immediately obvious because the arguments are written differently. Why does this have an `item` and `s' := destination item`, while the previous lemma has separate arguments for the components of the transition and has a definition for `item`?

2021-11-08 15:57 UTC, traiansf commented on VLSM/Equivocation.v
> +      := fun i => has_been_observed_capability_from_sent_received (IM i))
I actually use it as-is in more than one place, and rely that has_been_observed was built that way. But I agree that we could prove a more generic result if we wanted to.

2021-11-09 07:35 UTC, traiansf commented on VLSM/VLSMProjections.v
> +Record VLSM_weak_projection
I added a comment. In general yes, as proved for full_projections, any weak projection preserving initial states becomes a projection.

2021-11-09 08:50 UTC, traiansf commented on VLSM/Equivocation/FixedSetEquivocation.v
> +Definition generalized_fixed_equivocation s m : Prop
I agree that it would be nice to be able to have only one case here, and in general it would be nice if we could not special case the empty set of equivocators.

W.r.t. why can't have empty compositions, the reason is that we require the set of labels to be inhabited. However, we don't usually rely upon the non-emptiness of labels.
The only place we actually use the inhabitant of the label set is to spawn `NewMachine` copies for equivocators, and in that particular case we could slightly alter the definition of the Equivocator VLSM to add an extra label.

Maybe that would be a point to address in one of the meetings, as allowing empty compositions would indeed simplify some things.

2021-11-09 09:16 UTC, traiansf commented on VLSM/Equivocation/WitnessedEquivocation.v
> +are  included in the [equivocating_validators] for the source of its last
I think it is indeed impossible for it to be a strict inclusion; however, it's easier to use this way, as otherwise we might need to apply the previous lemma to show that the conditions of this lemma are satisfied.

Thanks for the remark about argument order.

2021-11-10 20:29 UTC, palmskog commented on VLSM/Equivocators/Composition/LimitedEquivocation/LimitedEquivocation.v
> +  (sender_safety :  can_emit_sender_safety_prop IM (fun i => i) sender)
```suggestion
  (sender_safety :  can_emit_sender_safety_prop IM id sender)
```

2021-11-10 20:37 UTC, palmskog approved these changes
Only very minor stuff to remark on, looks good to me in general.

2021-11-10 20:37 UTC, palmskog commented on VLSM/SubProjectionTraces.v
> +  destruct (decide _); [|contradiction].
```suggestion
  case_decide; [|contradiction].
```

2021-11-10 20:37 UTC, palmskog commented on VLSM/SubProjectionTraces.v
> +  destruct (decide _); [contradiction|].
```suggestion
  case_decide; [contradiction|].
```

2021-11-10 20:37 UTC, palmskog commented on VLSM/SubProjectionTraces.v
> +  destruct (decide _).
```suggestion
  case_decide.
```

2021-11-10 20:37 UTC, palmskog commented on VLSM/VLSMProjections.v
> +Definition VLSM_partial_projection_weaken : VLSM_weak_partial_projection X Y trace_project :=
Not sure I see the point about switching from `Lemma` to `Definition` below here (although it usually makes sense when there is a record, sure). You are still building `Prop`s, right? The usual distinction between `Definition` and `Lemma` is `Prop`-vs.non-`Prop`, rather than if `Proof. ... Qed.` is used.

2021-11-10 20:37 UTC, palmskog commented on VLSM/VLSMProjections.v
> +
Consider using `id` below instead of `fun x => x`.

2021-11-15 00:35 UTC, bmmoore approved these changes
I have a few further requests on the comments about constraint subsumptions, but everything else looks good.

2021-11-15 10:46 UTC, traiansf commented on VLSM/Equivocators/Composition/LimitedEquivocation/LimitedEquivocation.v
> +  (sender_safety :  can_emit_sender_safety_prop IM (fun i => i) sender)
I've changed in some other cases, but in this particular case it doesn't work. The reason is that the argument it is supposed to fill has different domain and codomain so it gets confused about using id

2021-11-16 14:48 UTC, palmskog commented on Lib/ListExtras.v
> +  rewrite elem_of_list_In. apply in_one_element_decompositions_iff.
Hmm, could it be worthwhile to instead translate `apply in_one_element_decompositions_iff.` and replace uses of it?

2021-11-16 14:48 UTC, palmskog commented on Lib/ListExtras.v
> +  apply NoDup_incl_length.
This proof shouldn't need going through `elem_of_list_In`. Not a big deal, but maybe make a TODO note.

2021-11-16 14:48 UTC, palmskog commented on VLSM/Equivocation/LimitedEquivocation.v
> +  (message_dependencies : message -> list message)
If you are indeed using this as a "listset", then I think you should keep the `set` moniker. I specifically preserved this in my list set layer for Stdpp.

2021-11-16 15:18 UTC, bmmoore approved these changes
Merge looks good

2021-11-16 15:18 UTC, bmmoore commented on Lib/ListExtras.v
> +  apply NoDup_incl_length.
It would be nice to avoid `NoDup_ListNoDup` here as well, but I don't see any nice stdpp lemmas that would apply.

2021-11-17 07:59 UTC, traiansf commented on Lib/ListExtras.v
> +  apply NoDup_incl_length.
Thanks for the advice. I managed to use `submseteq_length`.
For sets, `NoDup_submseteq` allows us to turn `⊆` into `⊆+` and then we can use the many lemmas available for `⊆+`

2021-11-17 08:13 UTC, merged