Purge stdlib list lemmas
runtimeverification/casper-cbc-proofs pull request #228
Opened 2021-09-27 18:54 UTC by palmskog

Towards fully using stdpp for all list related lemmas.

2021-11-10 11:09 UTC, palmskog commented
Overview of what happens in the PR:

- created a replacement for Stdlib's `ListSet` in `Lib/StdppListSet.v`
- port as many utility lemmas as possible to use the Stdpp listsets and notations (uses of `Listing` from Stdlib is kept)
- switch `In` to `∈`, `List.NoDup` to `NoDup`, `incl` to `⊆`, then use lemmas like `*_subseteq_*` and `*_elem_of_*`
- regress to using `NoDup_ListNoDup` and `elem_of_list_In` when there's seemingly no other way

2021-11-12 09:55 UTC, bmmoore requested changes
Conversions look okay, except NoDup_ListNoDup is used much more than necessary.

Almost all uses of NoDup_ListNoDup are just to get a stdpp NoDup from a stdlib Listing, and could be avoided with by defining a utility lemma for that. Most of the remaining uses I suggest how to avoid by using existing stdpp lemmas. (The one remaining case is converting to use our NoDup_remove, which doesn't seem to have a direct replacement).

I suggesd some improvements to a few places where the updated proofs were notably longer.

Remaining uses of elem_of_list_In doesn't have a majority cause like NoDup_ListNoDup, but maybe proving some more utility lemmas to centralize the the conversions into `Lib/` might be worthwhile.

2021-11-12 09:55 UTC, bmmoore commented on CBC/Definitions.v
> +            destruct Heq as [Heq|Heq].
Using more specific lemmas simplifies the proof a bit:
```
            rewrite elem_of_list_singleton in Heq.
            * inversion Heq; subst; tauto.
            * apply not_elem_of_nil.
```

2021-11-12 09:55 UTC, bmmoore commented on CBC/FullNodeSimpleVLSM.v
> +          split; try assumption.
Trailing whitespace
```suggestion
          split; try assumption.
```

2021-11-12 09:55 UTC, bmmoore commented on CBC/LightNode.v
> +        apply elem_of_list_In in H0.
`elem_of_list_bind` can replace `in_flat_map`, to avoid using `elem_of_list_In`

2021-11-12 09:55 UTC, bmmoore commented on VLSM/CBC/FullNode/Composite/LimitedEquivocation.v
> +        assumption.
```suggestion
        assumption.
```

2021-11-12 09:55 UTC, bmmoore commented on Lib/ListSetExtras.v
> +    apply elem_of_list_In.
```suggestion
    apply elem_of_list_fmap_1.
```

2021-11-12 09:55 UTC, bmmoore commented on Lib/ListSetExtras.v
>        apply (f_equal snd).
```suggestion
    * apply NoDup_fmap;[congruence|assumption].      
```

2021-11-12 09:55 UTC, bmmoore commented on VLSM/ListValidator/CommonFutures.v
>            intuition.
```suggestion
          apply NoDup_app in Hnodup. apply Hnodup.
```

2021-11-12 09:55 UTC, bmmoore commented on VLSM/ListValidator/CommonFutures.v
> +        assert (Hnx_li : x ∉ li). {
This can also be proven from NoDup_app, but takes a little reasoning afterwards:
```
          intro Hxli.
          apply NoDup_app in Hnodup as [_ [Hnlix _]].
          apply (Hnlix x Hxli).
          apply elem_of_list_singleton.
          reflexivity.
```

2021-11-12 09:55 UTC, bmmoore commented on VLSM/ListValidator/CommonFutures.v
> +        clear notX_In.
We can also avoid `List.NoDup` by using `NoDup_app`, but have to change how we get the `rev` for `notX`. Setoid rewriting by `Permutation` is one way:
```suggestion
      - apply NoDup_app in Hnodup.
        destruct Hnodup as [Hnodup [lfrom_notX _]].
        assert (notX: x ∉ (rev lfrom)). {
          intro Hx.
          apply (lfrom_notX x).
          rewrite <- Permutation_rev in Hx.
          assumption.
          apply elem_of_list_singleton.
          reflexivity.
        }
```

2021-11-12 09:55 UTC, bmmoore commented on VLSM/Equivocators/Composition/SimulatingFree/FullReplayTraces.v
> +    apply NoDup_remove in Hnodup.
Probably worth converting the `NoDup_remove` lemma using NoDup and elem_of rather than doing the `NoDup_ListNoDup` and also `elem_of_list_In` conversion inline here.

2021-11-12 20:10 UTC, palmskog commented
@bmmoore I removed nearly all uses of `NoDup_ListNoDup` and applied your suggestions. Can we maybe postpone a cleanup of `elem_of_list_In` until after the merge? I think there are already so many changes here that there is no obvious immediate gain from removing more `elem_of_list_In` right now.

2021-11-15 13:04 UTC, traiansf approved these changes

2021-11-15 15:05 UTC, bmmoore approved these changes

2021-11-15 15:07 UTC, bmmoore commented
Looks good. As I said, `elem_of_list_In` seems to be used for several different reasons and I didn't categorize them for you, so it's not so straightforward to eliminate them all right now.

2021-11-15 16:52 UTC, merged