Composite ELMO: first part.
runtimeverification/casper-cbc-proofs pull request #230
Opened 2021-10-06 16:23 UTC by h0nzZik

2021-10-18 14:10 UTC, h0nzZik commented on VLSM/ELMO/ELMO.v
> +  Lemma has_receive_observation_implies_is_protocol st idx m:
I actually use `protocol_trace_input_is_protocol` at the end of the proof.

2021-11-02 09:46 UTC, palmskog requested changes
This looks reasonable in general, but can we get a consistent style for use of blocks `{ ... }` in the proof script?

For example, I would recommend:

`{ intuition. }` consistently for one-liners

```
{
  intution.
  lia.
}
```
for multiple-liners.

2021-11-02 09:57 UTC, traiansf approved these changes
I'm ok with it being merged once Karl is satisfied with it.

2021-11-12 10:02 UTC, palmskog approved these changes
This now looks good, only thing that possiblty remains is to rebase on top of #228 if we merge that first.

2021-11-15 08:27 UTC, merged